## FIGURE 5 ##

library('tidyverse')
library('pheatmap')
library('viridis')
library('dendextend')
library('marmap')

setwd("../data")

# FIG 5 # Analysis of recent IBD sharing

# Load the COEFS file generated by IBIS all-in-one command
COEFS <- read.table("BARFRAY_703_ATL_IBIS_7_100_a0_maxDist_ALL.coef", sep='\t', header=T)
COEFS <- COEFS %>% select(-IBD2_Fraction)

# Load sample summer and winter coordinates (07/09/22) and extract winter1 positions
COORDS <- read.table("SAMPLE_SUMMER_WINTER_COORDS.txt", header=T)
COORDS <- arrange(COORDS, sample_filename)

# Extract Winter 1 coordinates
W1_COORDS <- COORDS %>% select(sample_filename,population,Winter1_X,Winter1_Y)

# Join Winter 1 coordinates for first individual in pairs
colnames(W1_COORDS)  <- c("Individual1", "POP1", "X1", "Y1")
COEFS <- left_join(COEFS, W1_COORDS,by=c("Individual1" = "Individual1"))

# Join Winter 1 coordinates for second individual in pairs
colnames(W1_COORDS)  <- c("Individual2", "POP2", "X2", "Y2")
COEFS <- left_join(COEFS,W1_COORDS,by='Individual2')

# Add Spawning stock information based on Winter latitude
COEFS <- COEFS %>% mutate(Stock1=case_when(Y1<=48~'BOB', Y1>48~'NS')) %>% mutate(Stock2=case_when(Y2<=48~'BOB', Y2>48~'NS'))

# Add information on regional spawning stock sharing for the pair
COEFS <- COEFS %>% mutate(Stock12=case_when(Stock1=='BOB' & Stock2=='BOB'~'BOB_BOB',Stock1=='NS' & Stock2=='NS'~'NS_NS',Stock1=='BOB' & Stock2=='NS'~'BOB_NS',Stock1=='NS' & Stock2=='BOB'~'BOB_NS'))

# Add relatedness information per pair
COEFS <- COEFS %>% mutate(Related=case_when(Kinship_Coefficient==0~'NO', Kinship_Coefficient>0~'YES'))

# FIG 5A # Heatmap of pairwise relatedness values with hierarchical clustering

# Add the pair of tagging sites for each pair of individuals, sorting sites alphabetically
COEFS_POPS <- COEFS %>% rowwise() %>% mutate(POP12 = paste(sort(c(POP1, POP2)), collapse = " - ")) %>% ungroup()

# Test difference in mean relatedness within vs between tagging locations:
W <- COEFS_POPS %>% filter(POP1==POP2) %>% select(Kinship_Coefficient)
B <- COEFS_POPS %>% filter(POP1!=POP2) %>% select(Kinship_Coefficient)
t.test(W,B)

# Calculate mean pairwise kinship coefficient for each pair of tagging sites
SITE_PAIR_IBD <- aggregate(Kinship_Coefficient ~ POP12, data = COEFS_POPS, FUN = mean,  na.rm = TRUE)
SITE_PAIR_IBD <- separate(SITE_PAIR_IBD, col = POP12, into = c("POP1", "POP2"), sep = " - ")

# Transform data frame into pairwise mean relatedness matrix
SITE_PAIR_IBD <- xtabs(Kinship_Coefficient ~ POP1 + POP2, data=SITE_PAIR_IBD)
SITE_PAIR_IBD[lower.tri(SITE_PAIR_IBD)] = t(SITE_PAIR_IBD)[lower.tri(SITE_PAIR_IBD)]

# Make hierarchical clustering of tagging site pairwise relatedness values
hclust_ibd <- hclust(dist(SITE_PAIR_IBD), method = "complete")

# Flip nodes to order samples locations (does not affect the tree)
loc_order <- c("CB","OL","NO","LT","AD","SQ","SM","CH","PB","DK")
hclust_ibd_col <- rotate(hclust_ibd, loc_order)
hclust_ibd_row <- rotate(hclust_ibd, loc_order)

# Prepare annotation colors
tree_col <- data.frame(cutree(hclust_ibd, k = 2))
colnames(tree_col) <- "cluster"
tree_col$cluster <- ifelse(tree_col$cluster==1, "cluster1","cluster2")

ices_col <- as.factor(c("BOB","BOB","NS","NS","BOB","BOB","BOB","NS","NS","NS"))
tree_col$ices <- ices_col

loc_col <- data.frame(location = loc_order)
row.names(loc_col) <- loc_col$location

fill <- colorRampPalette(c("blue","gold","red"))(10)

my_colour = list(
    location = c(CB=fill[10],OL=fill[9],NO=fill[8],LT=fill[7],AD=fill[6],SQ=fill[5],SM=fill[4],CH=fill[3],PB=fill[2],DK=fill[1]),
    ices = c(BOB="orange", NS="green"),
    cluster = c(cluster1="#ffb366", cluster2="lightgreen"))

# Make the plot
R1 <- pheatmap(SITE_PAIR_IBD, color = viridis(n = 256, alpha = 1, begin = 0, end = 1, direction = 1), breaks = seq(0, 3e-5, length.out = 257), fontsize_number = 10, cluster_rows = hclust_ibd_row, cluster_cols = hclust_ibd_col, annotation_colors = my_colour, annotation_row = tree_col, annotation_col = loc_col, treeheight_row = 0)


# FIG 5B # 

# Set Kinship Coefficient that are not degree <=7 to zero, to only consider recent relatedness
COEFS_7 <- mutate(COEFS, Related = ifelse(Kinship_Coefficient >0 & Degree == -1, "NO", Related))
COEFS_7 <- mutate(COEFS_7, Kinship_Coefficient = ifelse(Kinship_Coefficient >0 & Degree == -1, 0, Kinship_Coefficient))

# Proportion of related individuals per pair  
P_RELAT <- COEFS_7 %>% count(Stock12,Related) %>% na.exclude() %>% group_by(Stock12)  %>% mutate(freq = 100*(n/sum(n))) %>% filter(Related=="YES")

P_RELAT$Stock12 <- factor(P_RELAT$Stock12, levels = P_RELAT$Stock12)
myPal <- c("orange","grey","green")
R2 = ggplot(P_RELAT, aes(x = Stock12, y = freq)) + geom_bar(stat="identity",fill=myPal) + labs(x = "", y = "Percentage of related individuals") + theme_classic()


# FIG 5C # 

# Extract pairs with available Winter coordinates 
WW_COEFS <- COEFS %>% filter(Stock12=="BOB_BOB" | Stock12=="NS_NS" | Stock12=="BOB_NS")

# Load bathymetry on the northeast Atlantic
ATLF <- getNOAA.bathy(lon1=-15,lon2=12,lat1=35,lat2=55,resolution=2)
# Compute transition object with path impossible in waters deeper than -200m depth
trans <- trans.mat(ATLF,min.depth=50,max.depth=-200)

# Compute least cost distances for each pair of individual
# Dist_12 <- NULL
# for (i in 1:nrow(WW_COEFS))
#  {
#   Dist_12 <- c(Dist_12, lc.dist(trans, rbind(c(WW_COEFS$X1[i], WW_COEFS$Y1[i]),c(WW_COEFS$X2[i], WW_COEFS$Y2[i])), res ="dist"))
#  }

# Add pairwise distances for each pair of individual
WW_COEFS_DIST <- WW_COEFS %>% mutate(Dist_12=Dist_12)

# Remove aberrant distances
WW_COEFS_DIST <- mutate(WW_COEFS_DIST, Dist_12 = ifelse(Dist_12 > 3000, NA, Dist_12)) %>% drop_na(Dist_12)

# Bin the distance values into quantiles (equal number of points per bin), using 19 bins
n_bins <- 19
bins <- quantile(WW_COEFS_DIST$Dist_12, probs = seq(0, 1, length.out = n_bins + 1))
x_bins <- cut(WW_COEFS_DIST$Dist_12, breaks = bins, include.lowest = TRUE)
# Calculate midpoints for each bin
midpoints <- sapply(1:(length(bins) - 1), function(i) mean(bins[i:(i+1)]))
# Map midpoints to each bin
mid_x <- midpoints[as.numeric(x_bins)]

BOB_BOB <- WW_COEFS_DIST %>% filter(Stock12=="BOB_BOB") %>% pull(Kinship_Coefficient) %>% split(x_bins)
BOB_BOB_mean <- data.frame(unlist(lapply(BOB_BOB,mean)),midpoints)
colnames(BOB_BOB_mean) <- c("mean_kinship", "midpoints")
BOB_BOB.model <- lm(mean_kinship ~ midpoints, data=BOB_BOB_mean)
summary(BOB_BOB.model)

NS_NS <- WW_COEFS_DIST %>% filter(Stock12=="NS_NS") %>% pull(Kinship_Coefficient) %>% split(x_bins)
NS_NS_mean <- data.frame(unlist(lapply(NS_NS,mean)),midpoints)
colnames(NS_NS_mean) <- c("mean_kinship", "midpoints")
NS_NS.model <- lm(mean_kinship ~ midpoints, data=NS_NS_mean)
summary(NS_NS.model)

BOB_NS <- WW_COEFS_DIST %>% filter(Stock12=="BOB_NS") %>% pull(Kinship_Coefficient) %>% split(x_bins)
BOB_NS_mean <- data.frame(unlist(lapply(BOB_NS,mean)),midpoints)
colnames(BOB_NS_mean) <- c("mean_kinship", "midpoints")
BOB_NS.model = betareg(mean_kinship ~ midpoints, data=BOB_NS_mean)
summary(BOB_NS.model)

R3 <- ggplot(BOB_NS_mean, aes(x = midpoints, y = mean_kinship)) +
  geom_point(size = 2.5, shape = 21, colour="grey", fill="grey") +
  geom_line(aes(y = WW_COEFS_DIST %>% filter(Stock12=="BOB_BOB") %>% pull(Kinship_Coefficient) %>% mean(), colour = "BOB_BOB", linetype = "BOB_BOB")) +
  geom_line(aes(y = predict(BOB_NS.model, BOB_NS_mean), colour = "BOB_NS", linetype = "BOB_NS")) +
  geom_line(aes(y = WW_COEFS_DIST %>% filter(Stock12=="NS_NS") %>% pull(Kinship_Coefficient) %>% mean(), colour = "NS_NS", linetype = "NS_NS")) +
  scale_colour_manual("", values = c("orange", "grey", "green")) +
  scale_linetype_manual("", values = c("dashed", "solid", "dashed")) +
  ylim(0,2.5e-5) +
  theme_classic() +
  labs(x = "Distance between winter positions (km)", y = "Average kinship coefficient")
